/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutModel } from './WorkoutModel';
import {
    WorkoutModelFromJSON,
    WorkoutModelFromJSONTyped,
    WorkoutModelToJSON,
    WorkoutModelToJSONTyped,
} from './WorkoutModel';
import type { TrainingPlanModel } from './TrainingPlanModel';
import {
    TrainingPlanModelFromJSON,
    TrainingPlanModelFromJSONTyped,
    TrainingPlanModelToJSON,
    TrainingPlanModelToJSONTyped,
} from './TrainingPlanModel';
import type { WeeklyGoalModel } from './WeeklyGoalModel';
import {
    WeeklyGoalModelFromJSON,
    WeeklyGoalModelFromJSONTyped,
    WeeklyGoalModelToJSON,
    WeeklyGoalModelToJSONTyped,
} from './WeeklyGoalModel';

/**
 * 
 * @export
 * @interface AiPlannerResultModel
 */
export interface AiPlannerResultModel {
    /**
     * 
     * @type {TrainingPlanModel}
     * @memberof AiPlannerResultModel
     */
    trainingPlan: TrainingPlanModel;
    /**
     * 
     * @type {WeeklyGoalModel}
     * @memberof AiPlannerResultModel
     */
    weeklyGoal: WeeklyGoalModel;
    /**
     * 
     * @type {Array<WorkoutModel>}
     * @memberof AiPlannerResultModel
     */
    workouts: Array<WorkoutModel>;
    /**
     * 
     * @type {object}
     * @memberof AiPlannerResultModel
     */
    analysis: object;
    /**
     * 
     * @type {boolean}
     * @memberof AiPlannerResultModel
     */
    isAssessment: boolean;
}

/**
 * Check if a given object implements the AiPlannerResultModel interface.
 */
export function instanceOfAiPlannerResultModel(value: object): value is AiPlannerResultModel {
    if (!('trainingPlan' in value) || value['trainingPlan'] === undefined) return false;
    if (!('weeklyGoal' in value) || value['weeklyGoal'] === undefined) return false;
    if (!('workouts' in value) || value['workouts'] === undefined) return false;
    if (!('analysis' in value) || value['analysis'] === undefined) return false;
    if (!('isAssessment' in value) || value['isAssessment'] === undefined) return false;
    return true;
}

export function AiPlannerResultModelFromJSON(json: any): AiPlannerResultModel {
    return AiPlannerResultModelFromJSONTyped(json, false);
}

export function AiPlannerResultModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiPlannerResultModel {
    if (json == null) {
        return json;
    }
    return {
        
        'trainingPlan': TrainingPlanModelFromJSON(json['trainingPlan']),
        'weeklyGoal': WeeklyGoalModelFromJSON(json['weeklyGoal']),
        'workouts': ((json['workouts'] as Array<any>).map(WorkoutModelFromJSON)),
        'analysis': json['analysis'],
        'isAssessment': json['isAssessment'],
    };
}

export function AiPlannerResultModelToJSON(json: any): AiPlannerResultModel {
    return AiPlannerResultModelToJSONTyped(json, false);
}

export function AiPlannerResultModelToJSONTyped(value?: AiPlannerResultModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trainingPlan': TrainingPlanModelToJSON(value['trainingPlan']),
        'weeklyGoal': WeeklyGoalModelToJSON(value['weeklyGoal']),
        'workouts': ((value['workouts'] as Array<any>).map(WorkoutModelToJSON)),
        'analysis': value['analysis'],
        'isAssessment': value['isAssessment'],
    };
}

