/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerVerifyEmail200Response
 */
export interface AuthControllerVerifyEmail200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerVerifyEmail200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerVerifyEmail200Response interface.
 */
export function instanceOfAuthControllerVerifyEmail200Response(value: object): value is AuthControllerVerifyEmail200Response {
    return true;
}

export function AuthControllerVerifyEmail200ResponseFromJSON(json: any): AuthControllerVerifyEmail200Response {
    return AuthControllerVerifyEmail200ResponseFromJSONTyped(json, false);
}

export function AuthControllerVerifyEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerVerifyEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerVerifyEmail200ResponseToJSON(json: any): AuthControllerVerifyEmail200Response {
    return AuthControllerVerifyEmail200ResponseToJSONTyped(json, false);
}

export function AuthControllerVerifyEmail200ResponseToJSONTyped(value?: AuthControllerVerifyEmail200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

