/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';

/**
 * 
 * @export
 * @interface AuthPayload
 */
export interface AuthPayload {
    /**
     * 
     * @type {UserModel}
     * @memberof AuthPayload
     */
    user: UserModel;
    /**
     * 
     * @type {string}
     * @memberof AuthPayload
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthPayload
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AuthPayload interface.
 */
export function instanceOfAuthPayload(value: object): value is AuthPayload {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function AuthPayloadFromJSON(json: any): AuthPayload {
    return AuthPayloadFromJSONTyped(json, false);
}

export function AuthPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserModelFromJSON(json['user']),
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
    };
}

export function AuthPayloadToJSON(json: any): AuthPayload {
    return AuthPayloadToJSONTyped(json, false);
}

export function AuthPayloadToJSONTyped(value?: AuthPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserModelToJSON(value['user']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

