/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteWorkoutDto
 */
export interface CompleteWorkoutDto {
    /**
     * UUID of the HKWorkout that executed this prescribed workout
     * @type {string}
     * @memberof CompleteWorkoutDto
     */
    appleHealthWorkoutUUID?: string;
}

/**
 * Check if a given object implements the CompleteWorkoutDto interface.
 */
export function instanceOfCompleteWorkoutDto(value: object): value is CompleteWorkoutDto {
    return true;
}

export function CompleteWorkoutDtoFromJSON(json: any): CompleteWorkoutDto {
    return CompleteWorkoutDtoFromJSONTyped(json, false);
}

export function CompleteWorkoutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteWorkoutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'appleHealthWorkoutUUID': json['appleHealthWorkoutUUID'] == null ? undefined : json['appleHealthWorkoutUUID'],
    };
}

export function CompleteWorkoutDtoToJSON(json: any): CompleteWorkoutDto {
    return CompleteWorkoutDtoToJSONTyped(json, false);
}

export function CompleteWorkoutDtoToJSONTyped(value?: CompleteWorkoutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appleHealthWorkoutUUID': value['appleHealthWorkoutUUID'],
    };
}

