/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWaitlistEntryDto
 */
export interface CreateWaitlistEntryDto {
    /**
     * Nome completo
     * @type {string}
     * @memberof CreateWaitlistEntryDto
     */
    name: string;
    /**
     * Email para contato
     * @type {string}
     * @memberof CreateWaitlistEntryDto
     */
    email: string;
}

/**
 * Check if a given object implements the CreateWaitlistEntryDto interface.
 */
export function instanceOfCreateWaitlistEntryDto(value: object): value is CreateWaitlistEntryDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateWaitlistEntryDtoFromJSON(json: any): CreateWaitlistEntryDto {
    return CreateWaitlistEntryDtoFromJSONTyped(json, false);
}

export function CreateWaitlistEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWaitlistEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function CreateWaitlistEntryDtoToJSON(json: any): CreateWaitlistEntryDto {
    return CreateWaitlistEntryDtoToJSONTyped(json, false);
}

export function CreateWaitlistEntryDtoToJSONTyped(value?: CreateWaitlistEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

