/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutBlockInput } from './WorkoutBlockInput';
import {
    WorkoutBlockInputFromJSON,
    WorkoutBlockInputFromJSONTyped,
    WorkoutBlockInputToJSON,
    WorkoutBlockInputToJSONTyped,
} from './WorkoutBlockInput';

/**
 * 
 * @export
 * @interface CreateWorkoutInput
 */
export interface CreateWorkoutInput {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutInput
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutInput
     */
    trainingPlanId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutInput
     */
    weeklyGoalId?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateWorkoutInput
     */
    sportType: object;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutInput
     */
    description?: string;
    /**
     * 
     * @type {Array<WorkoutBlockInput>}
     * @memberof CreateWorkoutInput
     */
    blocks?: Array<WorkoutBlockInput>;
    /**
     * 
     * @type {object}
     * @memberof CreateWorkoutInput
     */
    status: object;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkoutInput
     */
    intensity?: number;
}

/**
 * Check if a given object implements the CreateWorkoutInput interface.
 */
export function instanceOfCreateWorkoutInput(value: object): value is CreateWorkoutInput {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('trainingPlanId' in value) || value['trainingPlanId'] === undefined) return false;
    if (!('sportType' in value) || value['sportType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateWorkoutInputFromJSON(json: any): CreateWorkoutInput {
    return CreateWorkoutInputFromJSONTyped(json, false);
}

export function CreateWorkoutInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkoutInput {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'trainingPlanId': json['trainingPlanId'],
        'weeklyGoalId': json['weeklyGoalId'] == null ? undefined : json['weeklyGoalId'],
        'sportType': json['sportType'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(WorkoutBlockInputFromJSON)),
        'status': json['status'],
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
    };
}

export function CreateWorkoutInputToJSON(json: any): CreateWorkoutInput {
    return CreateWorkoutInputToJSONTyped(json, false);
}

export function CreateWorkoutInputToJSONTyped(value?: CreateWorkoutInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'trainingPlanId': value['trainingPlanId'],
        'weeklyGoalId': value['weeklyGoalId'],
        'sportType': value['sportType'],
        'title': value['title'],
        'description': value['description'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(WorkoutBlockInputToJSON)),
        'status': value['status'],
        'intensity': value['intensity'],
    };
}

