/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTrainingPlanInput
 */
export interface CreateTrainingPlanInput {
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingPlanInput
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingPlanInput
     */
    objective: string;
    /**
     * 
     * @type {object}
     * @memberof CreateTrainingPlanInput
     */
    status: object;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingPlanInput
     */
    targetDate?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof CreateTrainingPlanInput
     */
    sports: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTrainingPlanInput
     */
    autoGenerate?: boolean;
}

/**
 * Check if a given object implements the CreateTrainingPlanInput interface.
 */
export function instanceOfCreateTrainingPlanInput(value: object): value is CreateTrainingPlanInput {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('objective' in value) || value['objective'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sports' in value) || value['sports'] === undefined) return false;
    return true;
}

export function CreateTrainingPlanInputFromJSON(json: any): CreateTrainingPlanInput {
    return CreateTrainingPlanInputFromJSONTyped(json, false);
}

export function CreateTrainingPlanInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrainingPlanInput {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'],
        'objective': json['objective'],
        'status': json['status'],
        'targetDate': json['targetDate'] == null ? undefined : json['targetDate'],
        'sports': json['sports'],
        'autoGenerate': json['autoGenerate'] == null ? undefined : json['autoGenerate'],
    };
}

export function CreateTrainingPlanInputToJSON(json: any): CreateTrainingPlanInput {
    return CreateTrainingPlanInputToJSONTyped(json, false);
}

export function CreateTrainingPlanInputToJSONTyped(value?: CreateTrainingPlanInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'],
        'objective': value['objective'],
        'status': value['status'],
        'targetDate': value['targetDate'],
        'sports': value['sports'],
        'autoGenerate': value['autoGenerate'],
    };
}

