/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGoalDto
 */
export interface CreateGoalDto {
    /**
     * Objetivo de corrida em texto livre
     * @type {string}
     * @memberof CreateGoalDto
     */
    goalText: string;
}

/**
 * Check if a given object implements the CreateGoalDto interface.
 */
export function instanceOfCreateGoalDto(value: object): value is CreateGoalDto {
    if (!('goalText' in value) || value['goalText'] === undefined) return false;
    return true;
}

export function CreateGoalDtoFromJSON(json: any): CreateGoalDto {
    return CreateGoalDtoFromJSONTyped(json, false);
}

export function CreateGoalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGoalDto {
    if (json == null) {
        return json;
    }
    return {
        
        'goalText': json['goalText'],
    };
}

export function CreateGoalDtoToJSON(json: any): CreateGoalDto {
    return CreateGoalDtoToJSONTyped(json, false);
}

export function CreateGoalDtoToJSONTyped(value?: CreateGoalDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goalText': value['goalText'],
    };
}

