/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquipmentInput
 */
export interface CreateEquipmentInput {
    /**
     * 
     * @type {string}
     * @memberof CreateEquipmentInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquipmentInput
     */
    imagePath: string;
}

/**
 * Check if a given object implements the CreateEquipmentInput interface.
 */
export function instanceOfCreateEquipmentInput(value: object): value is CreateEquipmentInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('imagePath' in value) || value['imagePath'] === undefined) return false;
    return true;
}

export function CreateEquipmentInputFromJSON(json: any): CreateEquipmentInput {
    return CreateEquipmentInputFromJSONTyped(json, false);
}

export function CreateEquipmentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquipmentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'imagePath': json['imagePath'],
    };
}

export function CreateEquipmentInputToJSON(json: any): CreateEquipmentInput {
    return CreateEquipmentInputToJSONTyped(json, false);
}

export function CreateEquipmentInputToJSONTyped(value?: CreateEquipmentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'imagePath': value['imagePath'],
    };
}

