/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SegmentDto } from './SegmentDto';
import {
    SegmentDtoFromJSON,
    SegmentDtoFromJSONTyped,
    SegmentDtoToJSON,
    SegmentDtoToJSONTyped,
} from './SegmentDto';

/**
 * 
 * @export
 * @interface DetailedSessionDto
 */
export interface DetailedSessionDto {
    /**
     * ISO 8601 start date of the run
     * @type {string}
     * @memberof DetailedSessionDto
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedSessionDto
     */
    appleHealthWorkoutUUID: string;
    /**
     * Prescribed Workout.id if the client resolved the link locally (SwiftData). If omitted, backend will attempt a same-day fallback match.
     * @type {string}
     * @memberof DetailedSessionDto
     */
    athlyWorkoutId?: string;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    distanceMeters: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    durationSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    averagePaceSecondsPerKm?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    avgHR?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    maxHR?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    activeEnergyBurned?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedSessionDto
     */
    elevationGainMeters?: number;
    /**
     * 
     * @type {Array<SegmentDto>}
     * @memberof DetailedSessionDto
     */
    segments: Array<SegmentDto>;
}

/**
 * Check if a given object implements the DetailedSessionDto interface.
 */
export function instanceOfDetailedSessionDto(value: object): value is DetailedSessionDto {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('appleHealthWorkoutUUID' in value) || value['appleHealthWorkoutUUID'] === undefined) return false;
    if (!('distanceMeters' in value) || value['distanceMeters'] === undefined) return false;
    if (!('durationSeconds' in value) || value['durationSeconds'] === undefined) return false;
    if (!('segments' in value) || value['segments'] === undefined) return false;
    return true;
}

export function DetailedSessionDtoFromJSON(json: any): DetailedSessionDto {
    return DetailedSessionDtoFromJSONTyped(json, false);
}

export function DetailedSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedSessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'],
        'appleHealthWorkoutUUID': json['appleHealthWorkoutUUID'],
        'athlyWorkoutId': json['athlyWorkoutId'] == null ? undefined : json['athlyWorkoutId'],
        'distanceMeters': json['distanceMeters'],
        'durationSeconds': json['durationSeconds'],
        'averagePaceSecondsPerKm': json['averagePaceSecondsPerKm'] == null ? undefined : json['averagePaceSecondsPerKm'],
        'avgHR': json['avgHR'] == null ? undefined : json['avgHR'],
        'maxHR': json['maxHR'] == null ? undefined : json['maxHR'],
        'activeEnergyBurned': json['activeEnergyBurned'] == null ? undefined : json['activeEnergyBurned'],
        'elevationGainMeters': json['elevationGainMeters'] == null ? undefined : json['elevationGainMeters'],
        'segments': ((json['segments'] as Array<any>).map(SegmentDtoFromJSON)),
    };
}

export function DetailedSessionDtoToJSON(json: any): DetailedSessionDto {
    return DetailedSessionDtoToJSONTyped(json, false);
}

export function DetailedSessionDtoToJSONTyped(value?: DetailedSessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'],
        'appleHealthWorkoutUUID': value['appleHealthWorkoutUUID'],
        'athlyWorkoutId': value['athlyWorkoutId'],
        'distanceMeters': value['distanceMeters'],
        'durationSeconds': value['durationSeconds'],
        'averagePaceSecondsPerKm': value['averagePaceSecondsPerKm'],
        'avgHR': value['avgHR'],
        'maxHR': value['maxHR'],
        'activeEnergyBurned': value['activeEnergyBurned'],
        'elevationGainMeters': value['elevationGainMeters'],
        'segments': ((value['segments'] as Array<any>).map(SegmentDtoToJSON)),
    };
}

