/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoalsDto
 */
export interface GoalsDto {
    /**
     * 
     * @type {string}
     * @memberof GoalsDto
     */
    practicesRegularly?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsDto
     */
    targetDistance?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GoalsDto
     */
    motivations?: Array<string>;
}

/**
 * Check if a given object implements the GoalsDto interface.
 */
export function instanceOfGoalsDto(value: object): value is GoalsDto {
    return true;
}

export function GoalsDtoFromJSON(json: any): GoalsDto {
    return GoalsDtoFromJSONTyped(json, false);
}

export function GoalsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'practicesRegularly': json['practicesRegularly'] == null ? undefined : json['practicesRegularly'],
        'targetDistance': json['targetDistance'] == null ? undefined : json['targetDistance'],
        'motivations': json['motivations'] == null ? undefined : json['motivations'],
    };
}

export function GoalsDtoToJSON(json: any): GoalsDto {
    return GoalsDtoToJSONTyped(json, false);
}

export function GoalsDtoToJSONTyped(value?: GoalsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'practicesRegularly': value['practicesRegularly'],
        'targetDistance': value['targetDistance'],
        'motivations': value['motivations'],
    };
}

