/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthRunItemDto
 */
export interface HealthRunItemDto {
    /**
     * ISO 8601 start date of the run
     * @type {string}
     * @memberof HealthRunItemDto
     */
    startDate: string;
    /**
     * 
     * @type {number}
     * @memberof HealthRunItemDto
     */
    distanceMeters: number;
    /**
     * 
     * @type {number}
     * @memberof HealthRunItemDto
     */
    durationSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof HealthRunItemDto
     */
    averagePaceSecondsPerKm?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthRunItemDto
     */
    activeEnergyBurned?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthRunItemDto
     */
    elevationGainMeters?: number;
}

/**
 * Check if a given object implements the HealthRunItemDto interface.
 */
export function instanceOfHealthRunItemDto(value: object): value is HealthRunItemDto {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('distanceMeters' in value) || value['distanceMeters'] === undefined) return false;
    if (!('durationSeconds' in value) || value['durationSeconds'] === undefined) return false;
    return true;
}

export function HealthRunItemDtoFromJSON(json: any): HealthRunItemDto {
    return HealthRunItemDtoFromJSONTyped(json, false);
}

export function HealthRunItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthRunItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'],
        'distanceMeters': json['distanceMeters'],
        'durationSeconds': json['durationSeconds'],
        'averagePaceSecondsPerKm': json['averagePaceSecondsPerKm'] == null ? undefined : json['averagePaceSecondsPerKm'],
        'activeEnergyBurned': json['activeEnergyBurned'] == null ? undefined : json['activeEnergyBurned'],
        'elevationGainMeters': json['elevationGainMeters'] == null ? undefined : json['elevationGainMeters'],
    };
}

export function HealthRunItemDtoToJSON(json: any): HealthRunItemDto {
    return HealthRunItemDtoToJSONTyped(json, false);
}

export function HealthRunItemDtoToJSONTyped(value?: HealthRunItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'],
        'distanceMeters': value['distanceMeters'],
        'durationSeconds': value['durationSeconds'],
        'averagePaceSecondsPerKm': value['averagePaceSecondsPerKm'],
        'activeEnergyBurned': value['activeEnergyBurned'],
        'elevationGainMeters': value['elevationGainMeters'],
    };
}

