/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationModel
 */
export interface IntegrationModel {
    /**
     * 
     * @type {string}
     * @memberof IntegrationModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationModel
     */
    icon: string;
    /**
     * 
     * @type {boolean}
     * @memberof IntegrationModel
     */
    connected: boolean;
    /**
     * 
     * @type {IntegrationModelTypeEnum}
     * @memberof IntegrationModel
     */
    type: IntegrationModelTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof IntegrationModel
     */
    stravaAthleteId?: object | null;
}


/**
 * @export
 */
export const IntegrationModelTypeEnum = {
    Strava: 'strava',
    Garmin: 'garmin',
    AppleHealth: 'apple_health',
    Other: 'other'
} as const;
export type IntegrationModelTypeEnum = typeof IntegrationModelTypeEnum[keyof typeof IntegrationModelTypeEnum];


/**
 * Check if a given object implements the IntegrationModel interface.
 */
export function instanceOfIntegrationModel(value: object): value is IntegrationModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('connected' in value) || value['connected'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function IntegrationModelFromJSON(json: any): IntegrationModel {
    return IntegrationModelFromJSONTyped(json, false);
}

export function IntegrationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'icon': json['icon'],
        'connected': json['connected'],
        'type': json['type'],
        'stravaAthleteId': json['stravaAthleteId'] == null ? undefined : json['stravaAthleteId'],
    };
}

export function IntegrationModelToJSON(json: any): IntegrationModel {
    return IntegrationModelToJSONTyped(json, false);
}

export function IntegrationModelToJSONTyped(value?: IntegrationModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon': value['icon'],
        'connected': value['connected'],
        'type': value['type'],
        'stravaAthleteId': value['stravaAthleteId'],
    };
}

