/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationsControllerGetStravaAuthUrl200Response
 */
export interface IntegrationsControllerGetStravaAuthUrl200Response {
    /**
     * 
     * @type {string}
     * @memberof IntegrationsControllerGetStravaAuthUrl200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the IntegrationsControllerGetStravaAuthUrl200Response interface.
 */
export function instanceOfIntegrationsControllerGetStravaAuthUrl200Response(value: object): value is IntegrationsControllerGetStravaAuthUrl200Response {
    return true;
}

export function IntegrationsControllerGetStravaAuthUrl200ResponseFromJSON(json: any): IntegrationsControllerGetStravaAuthUrl200Response {
    return IntegrationsControllerGetStravaAuthUrl200ResponseFromJSONTyped(json, false);
}

export function IntegrationsControllerGetStravaAuthUrl200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationsControllerGetStravaAuthUrl200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function IntegrationsControllerGetStravaAuthUrl200ResponseToJSON(json: any): IntegrationsControllerGetStravaAuthUrl200Response {
    return IntegrationsControllerGetStravaAuthUrl200ResponseToJSONTyped(json, false);
}

export function IntegrationsControllerGetStravaAuthUrl200ResponseToJSONTyped(value?: IntegrationsControllerGetStravaAuthUrl200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

