/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationsControllerSyncStrava200Response
 */
export interface IntegrationsControllerSyncStrava200Response {
    /**
     * 
     * @type {number}
     * @memberof IntegrationsControllerSyncStrava200Response
     */
    synced?: number;
}

/**
 * Check if a given object implements the IntegrationsControllerSyncStrava200Response interface.
 */
export function instanceOfIntegrationsControllerSyncStrava200Response(value: object): value is IntegrationsControllerSyncStrava200Response {
    return true;
}

export function IntegrationsControllerSyncStrava200ResponseFromJSON(json: any): IntegrationsControllerSyncStrava200Response {
    return IntegrationsControllerSyncStrava200ResponseFromJSONTyped(json, false);
}

export function IntegrationsControllerSyncStrava200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationsControllerSyncStrava200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'synced': json['synced'] == null ? undefined : json['synced'],
    };
}

export function IntegrationsControllerSyncStrava200ResponseToJSON(json: any): IntegrationsControllerSyncStrava200Response {
    return IntegrationsControllerSyncStrava200ResponseToJSONTyped(json, false);
}

export function IntegrationsControllerSyncStrava200ResponseToJSONTyped(value?: IntegrationsControllerSyncStrava200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'synced': value['synced'],
    };
}

