/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginInput
 */
export interface LoginInput {
    /**
     * 
     * @type {string}
     * @memberof LoginInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginInput
     */
    password: string;
}

/**
 * Check if a given object implements the LoginInput interface.
 */
export function instanceOfLoginInput(value: object): value is LoginInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginInputFromJSON(json: any): LoginInput {
    return LoginInputFromJSONTyped(json, false);
}

export function LoginInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginInputToJSON(json: any): LoginInput {
    return LoginInputToJSONTyped(json, false);
}

export function LoginInputToJSONTyped(value?: LoginInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

