/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParqDto
 */
export interface ParqDto {
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    heartCondition?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    chestPainDuringActivity?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    chestPainLastMonth?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    dizzinessOrLossOfConsciousness?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    boneJointProblem?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    takingBloodPressureMeds?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ParqDto
     */
    otherReasonToAvoidExercise?: boolean;
}

/**
 * Check if a given object implements the ParqDto interface.
 */
export function instanceOfParqDto(value: object): value is ParqDto {
    return true;
}

export function ParqDtoFromJSON(json: any): ParqDto {
    return ParqDtoFromJSONTyped(json, false);
}

export function ParqDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParqDto {
    if (json == null) {
        return json;
    }
    return {
        
        'heartCondition': json['heartCondition'] == null ? undefined : json['heartCondition'],
        'chestPainDuringActivity': json['chestPainDuringActivity'] == null ? undefined : json['chestPainDuringActivity'],
        'chestPainLastMonth': json['chestPainLastMonth'] == null ? undefined : json['chestPainLastMonth'],
        'dizzinessOrLossOfConsciousness': json['dizzinessOrLossOfConsciousness'] == null ? undefined : json['dizzinessOrLossOfConsciousness'],
        'boneJointProblem': json['boneJointProblem'] == null ? undefined : json['boneJointProblem'],
        'takingBloodPressureMeds': json['takingBloodPressureMeds'] == null ? undefined : json['takingBloodPressureMeds'],
        'otherReasonToAvoidExercise': json['otherReasonToAvoidExercise'] == null ? undefined : json['otherReasonToAvoidExercise'],
    };
}

export function ParqDtoToJSON(json: any): ParqDto {
    return ParqDtoToJSONTyped(json, false);
}

export function ParqDtoToJSONTyped(value?: ParqDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'heartCondition': value['heartCondition'],
        'chestPainDuringActivity': value['chestPainDuringActivity'],
        'chestPainLastMonth': value['chestPainLastMonth'],
        'dizzinessOrLossOfConsciousness': value['dizzinessOrLossOfConsciousness'],
        'boneJointProblem': value['boneJointProblem'],
        'takingBloodPressureMeds': value['takingBloodPressureMeds'],
        'otherReasonToAvoidExercise': value['otherReasonToAvoidExercise'],
    };
}

