/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceHealthDto
 */
export interface PerformanceHealthDto {
    /**
     * 
     * @type {string}
     * @memberof PerformanceHealthDto
     */
    referenceDistance?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceHealthDto
     */
    bestTime?: string;
    /**
     * 
     * @type {number}
     * @memberof PerformanceHealthDto
     */
    sleepQuality?: number;
    /**
     * 
     * @type {string}
     * @memberof PerformanceHealthDto
     */
    hasChronicPain?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceHealthDto
     */
    chronicPainDescription?: string;
}

/**
 * Check if a given object implements the PerformanceHealthDto interface.
 */
export function instanceOfPerformanceHealthDto(value: object): value is PerformanceHealthDto {
    return true;
}

export function PerformanceHealthDtoFromJSON(json: any): PerformanceHealthDto {
    return PerformanceHealthDtoFromJSONTyped(json, false);
}

export function PerformanceHealthDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceHealthDto {
    if (json == null) {
        return json;
    }
    return {
        
        'referenceDistance': json['referenceDistance'] == null ? undefined : json['referenceDistance'],
        'bestTime': json['bestTime'] == null ? undefined : json['bestTime'],
        'sleepQuality': json['sleepQuality'] == null ? undefined : json['sleepQuality'],
        'hasChronicPain': json['hasChronicPain'] == null ? undefined : json['hasChronicPain'],
        'chronicPainDescription': json['chronicPainDescription'] == null ? undefined : json['chronicPainDescription'],
    };
}

export function PerformanceHealthDtoToJSON(json: any): PerformanceHealthDto {
    return PerformanceHealthDtoToJSONTyped(json, false);
}

export function PerformanceHealthDtoToJSONTyped(value?: PerformanceHealthDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referenceDistance': value['referenceDistance'],
        'bestTime': value['bestTime'],
        'sleepQuality': value['sleepQuality'],
        'hasChronicPain': value['hasChronicPain'],
        'chronicPainDescription': value['chronicPainDescription'],
    };
}

