/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhysicalActivityDto
 */
export interface PhysicalActivityDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof PhysicalActivityDto
     */
    currentActivities?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PhysicalActivityDto
     */
    trainingPreparedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof PhysicalActivityDto
     */
    canRun3km?: string;
    /**
     * 
     * @type {string}
     * @memberof PhysicalActivityDto
     */
    runningExperience?: string;
}

/**
 * Check if a given object implements the PhysicalActivityDto interface.
 */
export function instanceOfPhysicalActivityDto(value: object): value is PhysicalActivityDto {
    return true;
}

export function PhysicalActivityDtoFromJSON(json: any): PhysicalActivityDto {
    return PhysicalActivityDtoFromJSONTyped(json, false);
}

export function PhysicalActivityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicalActivityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentActivities': json['currentActivities'] == null ? undefined : json['currentActivities'],
        'trainingPreparedBy': json['trainingPreparedBy'] == null ? undefined : json['trainingPreparedBy'],
        'canRun3km': json['canRun3km'] == null ? undefined : json['canRun3km'],
        'runningExperience': json['runningExperience'] == null ? undefined : json['runningExperience'],
    };
}

export function PhysicalActivityDtoToJSON(json: any): PhysicalActivityDto {
    return PhysicalActivityDtoToJSONTyped(json, false);
}

export function PhysicalActivityDtoToJSONTyped(value?: PhysicalActivityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentActivities': value['currentActivities'],
        'trainingPreparedBy': value['trainingPreparedBy'],
        'canRun3km': value['canRun3km'],
        'runningExperience': value['runningExperience'],
    };
}

