/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanNextWeekInput
 */
export interface PlanNextWeekInput {
    /**
     * 
     * @type {number}
     * @memberof PlanNextWeekInput
     */
    numberOfRuns?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanNextWeekInput
     */
    weekStartDate?: string;
}

/**
 * Check if a given object implements the PlanNextWeekInput interface.
 */
export function instanceOfPlanNextWeekInput(value: object): value is PlanNextWeekInput {
    return true;
}

export function PlanNextWeekInputFromJSON(json: any): PlanNextWeekInput {
    return PlanNextWeekInputFromJSONTyped(json, false);
}

export function PlanNextWeekInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanNextWeekInput {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfRuns': json['numberOfRuns'] == null ? undefined : json['numberOfRuns'],
        'weekStartDate': json['weekStartDate'] == null ? undefined : json['weekStartDate'],
    };
}

export function PlanNextWeekInputToJSON(json: any): PlanNextWeekInput {
    return PlanNextWeekInputToJSONTyped(json, false);
}

export function PlanNextWeekInputToJSONTyped(value?: PlanNextWeekInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfRuns': value['numberOfRuns'],
        'weekStartDate': value['weekStartDate'],
    };
}

