/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailedSessionDto } from './DetailedSessionDto';
import {
    DetailedSessionDtoFromJSON,
    DetailedSessionDtoFromJSONTyped,
    DetailedSessionDtoToJSON,
    DetailedSessionDtoToJSONTyped,
} from './DetailedSessionDto';
import type { HealthRunItemDto } from './HealthRunItemDto';
import {
    HealthRunItemDtoFromJSON,
    HealthRunItemDtoFromJSONTyped,
    HealthRunItemDtoToJSON,
    HealthRunItemDtoToJSONTyped,
} from './HealthRunItemDto';

/**
 * 
 * @export
 * @interface PlanFromHealthDto
 */
export interface PlanFromHealthDto {
    /**
     * Lightweight aggregated runs for historical context (up to 20 on first generation, 0 mid-plan).
     * @type {Array<HealthRunItemDto>}
     * @memberof PlanFromHealthDto
     */
    runs: Array<HealthRunItemDto>;
    /**
     * Rich per-segment sessions for execution analysis (5 on first generation, 7 mid-plan). Optional for backward compatibility.
     * @type {Array<DetailedSessionDto>}
     * @memberof PlanFromHealthDto
     */
    detailedSessions?: Array<DetailedSessionDto>;
    /**
     * Week start date (YYYY-MM-DD), defaults to next Monday
     * @type {string}
     * @memberof PlanFromHealthDto
     */
    weekStartDate?: string;
}

/**
 * Check if a given object implements the PlanFromHealthDto interface.
 */
export function instanceOfPlanFromHealthDto(value: object): value is PlanFromHealthDto {
    if (!('runs' in value) || value['runs'] === undefined) return false;
    return true;
}

export function PlanFromHealthDtoFromJSON(json: any): PlanFromHealthDto {
    return PlanFromHealthDtoFromJSONTyped(json, false);
}

export function PlanFromHealthDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanFromHealthDto {
    if (json == null) {
        return json;
    }
    return {
        
        'runs': ((json['runs'] as Array<any>).map(HealthRunItemDtoFromJSON)),
        'detailedSessions': json['detailedSessions'] == null ? undefined : ((json['detailedSessions'] as Array<any>).map(DetailedSessionDtoFromJSON)),
        'weekStartDate': json['weekStartDate'] == null ? undefined : json['weekStartDate'],
    };
}

export function PlanFromHealthDtoToJSON(json: any): PlanFromHealthDto {
    return PlanFromHealthDtoToJSONTyped(json, false);
}

export function PlanFromHealthDtoToJSONTyped(value?: PlanFromHealthDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runs': ((value['runs'] as Array<any>).map(HealthRunItemDtoToJSON)),
        'detailedSessions': value['detailedSessions'] == null ? undefined : ((value['detailedSessions'] as Array<any>).map(DetailedSessionDtoToJSON)),
        'weekStartDate': value['weekStartDate'],
    };
}

