/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SegmentDto
 */
export interface SegmentDto {
    /**
     * 
     * @type {SegmentDtoLabelEnum}
     * @memberof SegmentDto
     */
    label: SegmentDtoLabelEnum;
    /**
     * Rep index (1-based) when label = rep or rec
     * @type {number}
     * @memberof SegmentDto
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentDto
     */
    distanceKm: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentDto
     */
    durationSeconds: number;
    /**
     * Seconds per km
     * @type {number}
     * @memberof SegmentDto
     */
    avgPaceSecondsPerKm?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentDto
     */
    avgHR?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentDto
     */
    peakHR?: number;
    /**
     * HR at end of segment (useful for recovery deltas between reps)
     * @type {number}
     * @memberof SegmentDto
     */
    endHR?: number;
}


/**
 * @export
 */
export const SegmentDtoLabelEnum = {
    Warmup: 'warmup',
    Easy: 'easy',
    Tempo: 'tempo',
    Rep: 'rep',
    Rec: 'rec',
    Cooldown: 'cooldown'
} as const;
export type SegmentDtoLabelEnum = typeof SegmentDtoLabelEnum[keyof typeof SegmentDtoLabelEnum];


/**
 * Check if a given object implements the SegmentDto interface.
 */
export function instanceOfSegmentDto(value: object): value is SegmentDto {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('distanceKm' in value) || value['distanceKm'] === undefined) return false;
    if (!('durationSeconds' in value) || value['durationSeconds'] === undefined) return false;
    return true;
}

export function SegmentDtoFromJSON(json: any): SegmentDto {
    return SegmentDtoFromJSONTyped(json, false);
}

export function SegmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'index': json['index'] == null ? undefined : json['index'],
        'distanceKm': json['distanceKm'],
        'durationSeconds': json['durationSeconds'],
        'avgPaceSecondsPerKm': json['avgPaceSecondsPerKm'] == null ? undefined : json['avgPaceSecondsPerKm'],
        'avgHR': json['avgHR'] == null ? undefined : json['avgHR'],
        'peakHR': json['peakHR'] == null ? undefined : json['peakHR'],
        'endHR': json['endHR'] == null ? undefined : json['endHR'],
    };
}

export function SegmentDtoToJSON(json: any): SegmentDto {
    return SegmentDtoToJSONTyped(json, false);
}

export function SegmentDtoToJSONTyped(value?: SegmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'index': value['index'],
        'distanceKm': value['distanceKm'],
        'durationSeconds': value['durationSeconds'],
        'avgPaceSecondsPerKm': value['avgPaceSecondsPerKm'],
        'avgHR': value['avgHR'],
        'peakHR': value['peakHR'],
        'endHR': value['endHR'],
    };
}

