/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StravaCallbackInput
 */
export interface StravaCallbackInput {
    /**
     * 
     * @type {string}
     * @memberof StravaCallbackInput
     */
    code: string;
}

/**
 * Check if a given object implements the StravaCallbackInput interface.
 */
export function instanceOfStravaCallbackInput(value: object): value is StravaCallbackInput {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function StravaCallbackInputFromJSON(json: any): StravaCallbackInput {
    return StravaCallbackInputFromJSONTyped(json, false);
}

export function StravaCallbackInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StravaCallbackInput {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function StravaCallbackInputToJSON(json: any): StravaCallbackInput {
    return StravaCallbackInputToJSONTyped(json, false);
}

export function StravaCallbackInputToJSONTyped(value?: StravaCallbackInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

