/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitWorkoutFeedbackInput
 */
export interface SubmitWorkoutFeedbackInput {
    /**
     * 
     * @type {boolean}
     * @memberof SubmitWorkoutFeedbackInput
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof SubmitWorkoutFeedbackInput
     */
    effort: number;
    /**
     * 
     * @type {number}
     * @memberof SubmitWorkoutFeedbackInput
     */
    fatigue: number;
}

/**
 * Check if a given object implements the SubmitWorkoutFeedbackInput interface.
 */
export function instanceOfSubmitWorkoutFeedbackInput(value: object): value is SubmitWorkoutFeedbackInput {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('effort' in value) || value['effort'] === undefined) return false;
    if (!('fatigue' in value) || value['fatigue'] === undefined) return false;
    return true;
}

export function SubmitWorkoutFeedbackInputFromJSON(json: any): SubmitWorkoutFeedbackInput {
    return SubmitWorkoutFeedbackInputFromJSONTyped(json, false);
}

export function SubmitWorkoutFeedbackInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitWorkoutFeedbackInput {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'],
        'effort': json['effort'],
        'fatigue': json['fatigue'],
    };
}

export function SubmitWorkoutFeedbackInputToJSON(json: any): SubmitWorkoutFeedbackInput {
    return SubmitWorkoutFeedbackInputToJSONTyped(json, false);
}

export function SubmitWorkoutFeedbackInputToJSONTyped(value?: SubmitWorkoutFeedbackInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'effort': value['effort'],
        'fatigue': value['fatigue'],
    };
}

