/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhysicalActivityDto } from './PhysicalActivityDto';
import {
    PhysicalActivityDtoFromJSON,
    PhysicalActivityDtoFromJSONTyped,
    PhysicalActivityDtoToJSON,
    PhysicalActivityDtoToJSONTyped,
} from './PhysicalActivityDto';
import type { TrainingPlanningDto } from './TrainingPlanningDto';
import {
    TrainingPlanningDtoFromJSON,
    TrainingPlanningDtoFromJSONTyped,
    TrainingPlanningDtoToJSON,
    TrainingPlanningDtoToJSONTyped,
} from './TrainingPlanningDto';
import type { PerformanceHealthDto } from './PerformanceHealthDto';
import {
    PerformanceHealthDtoFromJSON,
    PerformanceHealthDtoFromJSONTyped,
    PerformanceHealthDtoToJSON,
    PerformanceHealthDtoToJSONTyped,
} from './PerformanceHealthDto';
import type { GoalsDto } from './GoalsDto';
import {
    GoalsDtoFromJSON,
    GoalsDtoFromJSONTyped,
    GoalsDtoToJSON,
    GoalsDtoToJSONTyped,
} from './GoalsDto';
import type { ParqDto } from './ParqDto';
import {
    ParqDtoFromJSON,
    ParqDtoFromJSONTyped,
    ParqDtoToJSON,
    ParqDtoToJSONTyped,
} from './ParqDto';

/**
 * 
 * @export
 * @interface SubmitAssessmentDto
 */
export interface SubmitAssessmentDto {
    /**
     * 
     * @type {GoalsDto}
     * @memberof SubmitAssessmentDto
     */
    goals: GoalsDto;
    /**
     * 
     * @type {PhysicalActivityDto}
     * @memberof SubmitAssessmentDto
     */
    activityHistory: PhysicalActivityDto;
    /**
     * 
     * @type {TrainingPlanningDto}
     * @memberof SubmitAssessmentDto
     */
    trainingPlanning: TrainingPlanningDto;
    /**
     * 
     * @type {PerformanceHealthDto}
     * @memberof SubmitAssessmentDto
     */
    performanceHealth: PerformanceHealthDto;
    /**
     * 
     * @type {ParqDto}
     * @memberof SubmitAssessmentDto
     */
    parq: ParqDto;
    /**
     * 
     * @type {string}
     * @memberof SubmitAssessmentDto
     */
    gender?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubmitAssessmentDto
     */
    termsAccepted: boolean;
}

/**
 * Check if a given object implements the SubmitAssessmentDto interface.
 */
export function instanceOfSubmitAssessmentDto(value: object): value is SubmitAssessmentDto {
    if (!('goals' in value) || value['goals'] === undefined) return false;
    if (!('activityHistory' in value) || value['activityHistory'] === undefined) return false;
    if (!('trainingPlanning' in value) || value['trainingPlanning'] === undefined) return false;
    if (!('performanceHealth' in value) || value['performanceHealth'] === undefined) return false;
    if (!('parq' in value) || value['parq'] === undefined) return false;
    if (!('termsAccepted' in value) || value['termsAccepted'] === undefined) return false;
    return true;
}

export function SubmitAssessmentDtoFromJSON(json: any): SubmitAssessmentDto {
    return SubmitAssessmentDtoFromJSONTyped(json, false);
}

export function SubmitAssessmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitAssessmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'goals': GoalsDtoFromJSON(json['goals']),
        'activityHistory': PhysicalActivityDtoFromJSON(json['activityHistory']),
        'trainingPlanning': TrainingPlanningDtoFromJSON(json['trainingPlanning']),
        'performanceHealth': PerformanceHealthDtoFromJSON(json['performanceHealth']),
        'parq': ParqDtoFromJSON(json['parq']),
        'gender': json['gender'] == null ? undefined : json['gender'],
        'termsAccepted': json['termsAccepted'],
    };
}

export function SubmitAssessmentDtoToJSON(json: any): SubmitAssessmentDto {
    return SubmitAssessmentDtoToJSONTyped(json, false);
}

export function SubmitAssessmentDtoToJSONTyped(value?: SubmitAssessmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goals': GoalsDtoToJSON(value['goals']),
        'activityHistory': PhysicalActivityDtoToJSON(value['activityHistory']),
        'trainingPlanning': TrainingPlanningDtoToJSON(value['trainingPlanning']),
        'performanceHealth': PerformanceHealthDtoToJSON(value['performanceHealth']),
        'parq': ParqDtoToJSON(value['parq']),
        'gender': value['gender'],
        'termsAccepted': value['termsAccepted'],
    };
}

