/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrainingPlanningDto
 */
export interface TrainingPlanningDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof TrainingPlanningDto
     */
    availableDays?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TrainingPlanningDto
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingPlanningDto
     */
    hasTargetDate?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingPlanningDto
     */
    targetDate?: string;
}

/**
 * Check if a given object implements the TrainingPlanningDto interface.
 */
export function instanceOfTrainingPlanningDto(value: object): value is TrainingPlanningDto {
    return true;
}

export function TrainingPlanningDtoFromJSON(json: any): TrainingPlanningDto {
    return TrainingPlanningDtoFromJSONTyped(json, false);
}

export function TrainingPlanningDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingPlanningDto {
    if (json == null) {
        return json;
    }
    return {
        
        'availableDays': json['availableDays'] == null ? undefined : json['availableDays'],
        'startDate': json['startDate'] == null ? undefined : json['startDate'],
        'hasTargetDate': json['hasTargetDate'] == null ? undefined : json['hasTargetDate'],
        'targetDate': json['targetDate'] == null ? undefined : json['targetDate'],
    };
}

export function TrainingPlanningDtoToJSON(json: any): TrainingPlanningDto {
    return TrainingPlanningDtoToJSONTyped(json, false);
}

export function TrainingPlanningDtoToJSONTyped(value?: TrainingPlanningDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableDays': value['availableDays'],
        'startDate': value['startDate'],
        'hasTargetDate': value['hasTargetDate'],
        'targetDate': value['targetDate'],
    };
}

