/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrainingPlanModel
 */
export interface TrainingPlanModel {
    /**
     * 
     * @type {string}
     * @memberof TrainingPlanModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingPlanModel
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingPlanModel
     */
    objective: string;
    /**
     * 
     * @type {Date}
     * @memberof TrainingPlanModel
     */
    targetDate?: Date | null;
    /**
     * 
     * @type {Array<TrainingPlanModelSportsEnum>}
     * @memberof TrainingPlanModel
     */
    sports: Array<TrainingPlanModelSportsEnum>;
    /**
     * 
     * @type {boolean}
     * @memberof TrainingPlanModel
     */
    autoGenerate: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TrainingPlanModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrainingPlanModel
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const TrainingPlanModelSportsEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type TrainingPlanModelSportsEnum = typeof TrainingPlanModelSportsEnum[keyof typeof TrainingPlanModelSportsEnum];


/**
 * Check if a given object implements the TrainingPlanModel interface.
 */
export function instanceOfTrainingPlanModel(value: object): value is TrainingPlanModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('objective' in value) || value['objective'] === undefined) return false;
    if (!('sports' in value) || value['sports'] === undefined) return false;
    if (!('autoGenerate' in value) || value['autoGenerate'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TrainingPlanModelFromJSON(json: any): TrainingPlanModel {
    return TrainingPlanModelFromJSONTyped(json, false);
}

export function TrainingPlanModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingPlanModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startDate': json['startDate'],
        'objective': json['objective'],
        'targetDate': json['targetDate'] == null ? undefined : (new Date(json['targetDate'])),
        'sports': json['sports'],
        'autoGenerate': json['autoGenerate'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function TrainingPlanModelToJSON(json: any): TrainingPlanModel {
    return TrainingPlanModelToJSONTyped(json, false);
}

export function TrainingPlanModelToJSONTyped(value?: TrainingPlanModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'startDate': value['startDate'],
        'objective': value['objective'],
        'targetDate': value['targetDate'] == null ? value['targetDate'] : value['targetDate'].toISOString(),
        'sports': value['sports'],
        'autoGenerate': value['autoGenerate'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

