/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWeeklyGoalInput
 */
export interface UpdateWeeklyGoalInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateWeeklyGoalInput
     */
    weekStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWeeklyGoalInput
     */
    weekEndDate?: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateWeeklyGoalInput
     */
    status?: object;
    /**
     * 
     * @type {object}
     * @memberof UpdateWeeklyGoalInput
     */
    metrics?: object;
}

/**
 * Check if a given object implements the UpdateWeeklyGoalInput interface.
 */
export function instanceOfUpdateWeeklyGoalInput(value: object): value is UpdateWeeklyGoalInput {
    return true;
}

export function UpdateWeeklyGoalInputFromJSON(json: any): UpdateWeeklyGoalInput {
    return UpdateWeeklyGoalInputFromJSONTyped(json, false);
}

export function UpdateWeeklyGoalInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWeeklyGoalInput {
    if (json == null) {
        return json;
    }
    return {
        
        'weekStartDate': json['weekStartDate'] == null ? undefined : json['weekStartDate'],
        'weekEndDate': json['weekEndDate'] == null ? undefined : json['weekEndDate'],
        'status': json['status'] == null ? undefined : json['status'],
        'metrics': json['metrics'] == null ? undefined : json['metrics'],
    };
}

export function UpdateWeeklyGoalInputToJSON(json: any): UpdateWeeklyGoalInput {
    return UpdateWeeklyGoalInputToJSONTyped(json, false);
}

export function UpdateWeeklyGoalInputToJSONTyped(value?: UpdateWeeklyGoalInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weekStartDate': value['weekStartDate'],
        'weekEndDate': value['weekEndDate'],
        'status': value['status'],
        'metrics': value['metrics'],
    };
}

