/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTrainingPlanInput
 */
export interface UpdateTrainingPlanInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingPlanInput
     */
    startDate?: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateTrainingPlanInput
     */
    weeks?: object;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingPlanInput
     */
    objective?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingPlanInput
     */
    targetDate?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof UpdateTrainingPlanInput
     */
    sports: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTrainingPlanInput
     */
    autoGenerate?: boolean;
}

/**
 * Check if a given object implements the UpdateTrainingPlanInput interface.
 */
export function instanceOfUpdateTrainingPlanInput(value: object): value is UpdateTrainingPlanInput {
    if (!('sports' in value) || value['sports'] === undefined) return false;
    return true;
}

export function UpdateTrainingPlanInputFromJSON(json: any): UpdateTrainingPlanInput {
    return UpdateTrainingPlanInputFromJSONTyped(json, false);
}

export function UpdateTrainingPlanInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrainingPlanInput {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'] == null ? undefined : json['startDate'],
        'weeks': json['weeks'] == null ? undefined : json['weeks'],
        'objective': json['objective'] == null ? undefined : json['objective'],
        'targetDate': json['targetDate'] == null ? undefined : json['targetDate'],
        'sports': json['sports'],
        'autoGenerate': json['autoGenerate'] == null ? undefined : json['autoGenerate'],
    };
}

export function UpdateTrainingPlanInputToJSON(json: any): UpdateTrainingPlanInput {
    return UpdateTrainingPlanInputToJSONTyped(json, false);
}

export function UpdateTrainingPlanInputToJSONTyped(value?: UpdateTrainingPlanInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'],
        'weeks': value['weeks'],
        'objective': value['objective'],
        'targetDate': value['targetDate'],
        'sports': value['sports'],
        'autoGenerate': value['autoGenerate'],
    };
}

