/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutBlockInput } from './WorkoutBlockInput';
import {
    WorkoutBlockInputFromJSON,
    WorkoutBlockInputFromJSONTyped,
    WorkoutBlockInputToJSON,
    WorkoutBlockInputToJSONTyped,
} from './WorkoutBlockInput';

/**
 * 
 * @export
 * @interface UpdateWorkoutInput
 */
export interface UpdateWorkoutInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkoutInput
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkoutInput
     */
    description?: string;
    /**
     * 
     * @type {Array<WorkoutBlockInput>}
     * @memberof UpdateWorkoutInput
     */
    blocks?: Array<WorkoutBlockInput>;
    /**
     * 
     * @type {number}
     * @memberof UpdateWorkoutInput
     */
    intensity?: number;
    /**
     * 
     * @type {UpdateWorkoutInputStatusEnum}
     * @memberof UpdateWorkoutInput
     */
    status?: UpdateWorkoutInputStatusEnum;
    /**
     * 
     * @type {UpdateWorkoutInputSportTypeEnum}
     * @memberof UpdateWorkoutInput
     */
    sportType?: UpdateWorkoutInputSportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkoutInput
     */
    date?: string;
}


/**
 * @export
 */
export const UpdateWorkoutInputStatusEnum = {
    Scheduled: 'scheduled',
    Done: 'done',
    Skipped: 'skipped',
    Partial: 'partial'
} as const;
export type UpdateWorkoutInputStatusEnum = typeof UpdateWorkoutInputStatusEnum[keyof typeof UpdateWorkoutInputStatusEnum];

/**
 * @export
 */
export const UpdateWorkoutInputSportTypeEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type UpdateWorkoutInputSportTypeEnum = typeof UpdateWorkoutInputSportTypeEnum[keyof typeof UpdateWorkoutInputSportTypeEnum];


/**
 * Check if a given object implements the UpdateWorkoutInput interface.
 */
export function instanceOfUpdateWorkoutInput(value: object): value is UpdateWorkoutInput {
    return true;
}

export function UpdateWorkoutInputFromJSON(json: any): UpdateWorkoutInput {
    return UpdateWorkoutInputFromJSONTyped(json, false);
}

export function UpdateWorkoutInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkoutInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(WorkoutBlockInputFromJSON)),
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
        'status': json['status'] == null ? undefined : json['status'],
        'sportType': json['sportType'] == null ? undefined : json['sportType'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function UpdateWorkoutInputToJSON(json: any): UpdateWorkoutInput {
    return UpdateWorkoutInputToJSONTyped(json, false);
}

export function UpdateWorkoutInputToJSONTyped(value?: UpdateWorkoutInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(WorkoutBlockInputToJSON)),
        'intensity': value['intensity'],
        'status': value['status'],
        'sportType': value['sportType'],
        'date': value['date'],
    };
}

