/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEquipmentInput
 */
export interface UpdateEquipmentInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentInput
     */
    imagePath?: string;
}

/**
 * Check if a given object implements the UpdateEquipmentInput interface.
 */
export function instanceOfUpdateEquipmentInput(value: object): value is UpdateEquipmentInput {
    return true;
}

export function UpdateEquipmentInputFromJSON(json: any): UpdateEquipmentInput {
    return UpdateEquipmentInputFromJSONTyped(json, false);
}

export function UpdateEquipmentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEquipmentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'imagePath': json['imagePath'] == null ? undefined : json['imagePath'],
    };
}

export function UpdateEquipmentInputToJSON(json: any): UpdateEquipmentInput {
    return UpdateEquipmentInputToJSONTyped(json, false);
}

export function UpdateEquipmentInputToJSONTyped(value?: UpdateEquipmentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'imagePath': value['imagePath'],
    };
}

