/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailDto
     */
    otp: string;
}

/**
 * Check if a given object implements the VerifyEmailDto interface.
 */
export function instanceOfVerifyEmailDto(value: object): value is VerifyEmailDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('otp' in value) || value['otp'] === undefined) return false;
    return true;
}

export function VerifyEmailDtoFromJSON(json: any): VerifyEmailDto {
    return VerifyEmailDtoFromJSONTyped(json, false);
}

export function VerifyEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'otp': json['otp'],
    };
}

export function VerifyEmailDtoToJSON(json: any): VerifyEmailDto {
    return VerifyEmailDtoToJSONTyped(json, false);
}

export function VerifyEmailDtoToJSONTyped(value?: VerifyEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'otp': value['otp'],
    };
}

