/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeeklyGoalModel
 */
export interface WeeklyGoalModel {
    /**
     * 
     * @type {string}
     * @memberof WeeklyGoalModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyGoalModel
     */
    trainingPlanId: string;
    /**
     * 
     * @type {Date}
     * @memberof WeeklyGoalModel
     */
    weekStartDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof WeeklyGoalModel
     */
    weekEndDate: Date;
    /**
     * 
     * @type {WeeklyGoalModelStatusEnum}
     * @memberof WeeklyGoalModel
     */
    status: WeeklyGoalModelStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof WeeklyGoalModel
     */
    metrics?: object;
    /**
     * 
     * @type {Date}
     * @memberof WeeklyGoalModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WeeklyGoalModel
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const WeeklyGoalModelStatusEnum = {
    Planned: 'PLANNED',
    Generated: 'GENERATED',
    Cancelled: 'CANCELLED',
    Locked: 'LOCKED'
} as const;
export type WeeklyGoalModelStatusEnum = typeof WeeklyGoalModelStatusEnum[keyof typeof WeeklyGoalModelStatusEnum];


/**
 * Check if a given object implements the WeeklyGoalModel interface.
 */
export function instanceOfWeeklyGoalModel(value: object): value is WeeklyGoalModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('trainingPlanId' in value) || value['trainingPlanId'] === undefined) return false;
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('weekEndDate' in value) || value['weekEndDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WeeklyGoalModelFromJSON(json: any): WeeklyGoalModel {
    return WeeklyGoalModelFromJSONTyped(json, false);
}

export function WeeklyGoalModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeeklyGoalModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'trainingPlanId': json['trainingPlanId'],
        'weekStartDate': (new Date(json['weekStartDate'])),
        'weekEndDate': (new Date(json['weekEndDate'])),
        'status': json['status'],
        'metrics': json['metrics'] == null ? undefined : json['metrics'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function WeeklyGoalModelToJSON(json: any): WeeklyGoalModel {
    return WeeklyGoalModelToJSONTyped(json, false);
}

export function WeeklyGoalModelToJSONTyped(value?: WeeklyGoalModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'trainingPlanId': value['trainingPlanId'],
        'weekStartDate': value['weekStartDate'].toISOString(),
        'weekEndDate': value['weekEndDate'].toISOString(),
        'status': value['status'],
        'metrics': value['metrics'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

