/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutBlock } from './WorkoutBlock';
import {
    WorkoutBlockFromJSON,
    WorkoutBlockFromJSONTyped,
    WorkoutBlockToJSON,
    WorkoutBlockToJSONTyped,
} from './WorkoutBlock';

/**
 * 
 * @export
 * @interface WorkoutModel
 */
export interface WorkoutModel {
    /**
     * 
     * @type {string}
     * @memberof WorkoutModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkoutModel
     */
    date: string;
    /**
     * 
     * @type {WorkoutModelSportTypeEnum}
     * @memberof WorkoutModel
     */
    sportType: WorkoutModelSportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkoutModel
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof WorkoutModel
     */
    description?: string;
    /**
     * 
     * @type {Array<WorkoutBlock>}
     * @memberof WorkoutModel
     */
    blocks: Array<WorkoutBlock>;
    /**
     * 
     * @type {WorkoutModelStatusEnum}
     * @memberof WorkoutModel
     */
    status: WorkoutModelStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkoutModel
     */
    trainingPlanId?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkoutModel
     */
    weeklyGoalId?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkoutModel
     */
    intensity?: number;
    /**
     * 
     * @type {object}
     * @memberof WorkoutModel
     */
    stravaActivityId?: object | null;
}


/**
 * @export
 */
export const WorkoutModelSportTypeEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type WorkoutModelSportTypeEnum = typeof WorkoutModelSportTypeEnum[keyof typeof WorkoutModelSportTypeEnum];

/**
 * @export
 */
export const WorkoutModelStatusEnum = {
    Scheduled: 'scheduled',
    Done: 'done',
    Skipped: 'skipped',
    Partial: 'partial'
} as const;
export type WorkoutModelStatusEnum = typeof WorkoutModelStatusEnum[keyof typeof WorkoutModelStatusEnum];


/**
 * Check if a given object implements the WorkoutModel interface.
 */
export function instanceOfWorkoutModel(value: object): value is WorkoutModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('sportType' in value) || value['sportType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('blocks' in value) || value['blocks'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WorkoutModelFromJSON(json: any): WorkoutModel {
    return WorkoutModelFromJSONTyped(json, false);
}

export function WorkoutModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': json['date'],
        'sportType': json['sportType'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'blocks': ((json['blocks'] as Array<any>).map(WorkoutBlockFromJSON)),
        'status': json['status'],
        'trainingPlanId': json['trainingPlanId'] == null ? undefined : json['trainingPlanId'],
        'weeklyGoalId': json['weeklyGoalId'] == null ? undefined : json['weeklyGoalId'],
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
        'stravaActivityId': json['stravaActivityId'] == null ? undefined : json['stravaActivityId'],
    };
}

export function WorkoutModelToJSON(json: any): WorkoutModel {
    return WorkoutModelToJSONTyped(json, false);
}

export function WorkoutModelToJSONTyped(value?: WorkoutModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'],
        'sportType': value['sportType'],
        'title': value['title'],
        'description': value['description'],
        'blocks': ((value['blocks'] as Array<any>).map(WorkoutBlockToJSON)),
        'status': value['status'],
        'trainingPlanId': value['trainingPlanId'],
        'weeklyGoalId': value['weeklyGoalId'],
        'intensity': value['intensity'],
        'stravaActivityId': value['stravaActivityId'],
    };
}

