/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkoutBlockInput
 */
export interface WorkoutBlockInput {
    /**
     * 
     * @type {string}
     * @memberof WorkoutBlockInput
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof WorkoutBlockInput
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkoutBlockInput
     */
    distance?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkoutBlockInput
     */
    targetPace?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkoutBlockInput
     */
    instructions?: string;
}

/**
 * Check if a given object implements the WorkoutBlockInput interface.
 */
export function instanceOfWorkoutBlockInput(value: object): value is WorkoutBlockInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WorkoutBlockInputFromJSON(json: any): WorkoutBlockInput {
    return WorkoutBlockInputFromJSONTyped(json, false);
}

export function WorkoutBlockInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutBlockInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'targetPace': json['targetPace'] == null ? undefined : json['targetPace'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
    };
}

export function WorkoutBlockInputToJSON(json: any): WorkoutBlockInput {
    return WorkoutBlockInputToJSONTyped(json, false);
}

export function WorkoutBlockInputToJSONTyped(value?: WorkoutBlockInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'duration': value['duration'],
        'distance': value['distance'],
        'targetPace': value['targetPace'],
        'instructions': value['instructions'],
    };
}

