/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkoutFeedbackModel
 */
export interface WorkoutFeedbackModel {
    /**
     * 
     * @type {string}
     * @memberof WorkoutFeedbackModel
     */
    workoutId: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkoutFeedbackModel
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof WorkoutFeedbackModel
     */
    effort: number;
    /**
     * 
     * @type {number}
     * @memberof WorkoutFeedbackModel
     */
    fatigue: number;
}

/**
 * Check if a given object implements the WorkoutFeedbackModel interface.
 */
export function instanceOfWorkoutFeedbackModel(value: object): value is WorkoutFeedbackModel {
    if (!('workoutId' in value) || value['workoutId'] === undefined) return false;
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('effort' in value) || value['effort'] === undefined) return false;
    if (!('fatigue' in value) || value['fatigue'] === undefined) return false;
    return true;
}

export function WorkoutFeedbackModelFromJSON(json: any): WorkoutFeedbackModel {
    return WorkoutFeedbackModelFromJSONTyped(json, false);
}

export function WorkoutFeedbackModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutFeedbackModel {
    if (json == null) {
        return json;
    }
    return {
        
        'workoutId': json['workoutId'],
        'completed': json['completed'],
        'effort': json['effort'],
        'fatigue': json['fatigue'],
    };
}

export function WorkoutFeedbackModelToJSON(json: any): WorkoutFeedbackModel {
    return WorkoutFeedbackModelToJSONTyped(json, false);
}

export function WorkoutFeedbackModelToJSONTyped(value?: WorkoutFeedbackModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workoutId': value['workoutId'],
        'completed': value['completed'],
        'effort': value['effort'],
        'fatigue': value['fatigue'],
    };
}

