/**
 * Identificadores estáveis dos erros da API.
 *
 * O backend continua enviando `message` em pt-BR (clientes web/Android ainda mostram esse
 * texto, e ele serve de fallback e de contexto nos logs), mas o `code` é o contrato de
 * verdade: é por ele que o app escolhe a string traduzida no próprio catálogo de idiomas.
 *
 * Um código, uma vez publicado, não muda — renomear quebra clientes já instalados. Para um
 * significado novo, acrescente um código novo.
 */
export const ErrorCode = {
  // Autenticação
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_SOCIAL_ACCOUNT_NO_PASSWORD: 'AUTH_SOCIAL_ACCOUNT_NO_PASSWORD',
  AUTH_SOCIAL_ACCOUNT_UNIDENTIFIED: 'AUTH_SOCIAL_ACCOUNT_UNIDENTIFIED',
  AUTH_RESET_CODE_INVALID: 'AUTH_RESET_CODE_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_GOOGLE_NOT_CONFIGURED: 'AUTH_GOOGLE_NOT_CONFIGURED',
  AUTH_GOOGLE_TOKEN_INVALID: 'AUTH_GOOGLE_TOKEN_INVALID',
  AUTH_GOOGLE_ALREADY_LINKED: 'AUTH_GOOGLE_ALREADY_LINKED',
  AUTH_APPLE_NOT_CONFIGURED: 'AUTH_APPLE_NOT_CONFIGURED',
  AUTH_APPLE_TOKEN_INVALID: 'AUTH_APPLE_TOKEN_INVALID',
  AUTH_APPLE_ALREADY_LINKED: 'AUTH_APPLE_ALREADY_LINKED',
  AUTH_LAST_CREDENTIAL: 'AUTH_LAST_CREDENTIAL',
  AUTH_ADMIN_ACCESS_DENIED: 'AUTH_ADMIN_ACCESS_DENIED',

  // Usuário
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Assinatura
  BILLING_SUBSCRIPTION_REQUIRED: 'BILLING_SUBSCRIPTION_REQUIRED',
  BILLING_WEBHOOK_UNAUTHORIZED: 'BILLING_WEBHOOK_UNAUTHORIZED',

  // Lista de espera
  WAITLIST_EMAIL_ALREADY_REGISTERED: 'WAITLIST_EMAIL_ALREADY_REGISTERED',

  // Avaliação
  ASSESSMENT_TERMS_NOT_ACCEPTED: 'ASSESSMENT_TERMS_NOT_ACCEPTED',
  ASSESSMENT_PLAN_GENERATION_IN_PROGRESS: 'ASSESSMENT_PLAN_GENERATION_IN_PROGRESS',

  // Treinos
  WORKOUT_NOT_FOUND: 'WORKOUT_NOT_FOUND',
  WORKOUT_FEEDBACK_FAILED: 'WORKOUT_FEEDBACK_FAILED',
  WORKOUT_COMPLETE_FAILED: 'WORKOUT_COMPLETE_FAILED',

  // Metas semanais
  WEEKLY_GOAL_NOT_FOUND: 'WEEKLY_GOAL_NOT_FOUND',

  // Planos de treino
  TRAINING_PLAN_NOT_FOUND: 'TRAINING_PLAN_NOT_FOUND',
  TRAINING_PLAN_ALREADY_EXISTS: 'TRAINING_PLAN_ALREADY_EXISTS',
  TRAINING_PLAN_LOCKED: 'TRAINING_PLAN_LOCKED',
  TRAINING_PLAN_CLOSED: 'TRAINING_PLAN_CLOSED',
  WEEKLY_PLAN_ALREADY_EXISTS: 'WEEKLY_PLAN_ALREADY_EXISTS',
  WEEKLY_PLAN_GENERATION_IN_PROGRESS: 'WEEKLY_PLAN_GENERATION_IN_PROGRESS',

  // Equipamentos
  EQUIPMENT_NOT_FOUND: 'EQUIPMENT_NOT_FOUND',

  // Geração por IA
  PLAN_GENERATION_NOT_FOUND: 'PLAN_GENERATION_NOT_FOUND',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_PLAN_GENERATION_FAILED: 'AI_PLAN_GENERATION_FAILED',

  // Validação de payload (class-validator)
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
