/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AiPlannerControllerPlanNextWeekRequest {
    body: object;
}

/**
 * 
 */
export class AiPlannerApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiPlannerControllerPlanNextWeek without sending the request
     */
    async aiPlannerControllerPlanNextWeekRequestOpts(requestParameters: AiPlannerControllerPlanNextWeekRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling aiPlannerControllerPlanNextWeek().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ai-planner/plan-next-week`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async aiPlannerControllerPlanNextWeekRaw(requestParameters: AiPlannerControllerPlanNextWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.aiPlannerControllerPlanNextWeekRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async aiPlannerControllerPlanNextWeek(requestParameters: AiPlannerControllerPlanNextWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.aiPlannerControllerPlanNextWeekRaw(requestParameters, initOverrides);
    }

}
