/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SubmitAssessmentDto,
} from '../models/index';
import {
    SubmitAssessmentDtoFromJSON,
    SubmitAssessmentDtoToJSON,
} from '../models/index';

export interface AssessmentControllerSubmitRequest {
    submitAssessmentDto: SubmitAssessmentDto;
}

/**
 * 
 */
export class AssessmentApi extends runtime.BaseAPI {

    /**
     * Creates request options for assessmentControllerFindMine without sending the request
     */
    async assessmentControllerFindMineRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/assessment`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current user assessment answers
     */
    async assessmentControllerFindMineRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.assessmentControllerFindMineRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the current user assessment answers
     */
    async assessmentControllerFindMine(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.assessmentControllerFindMineRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for assessmentControllerSubmit without sending the request
     */
    async assessmentControllerSubmitRequestOpts(requestParameters: AssessmentControllerSubmitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['submitAssessmentDto'] == null) {
            throw new runtime.RequiredError(
                'submitAssessmentDto',
                'Required parameter "submitAssessmentDto" was null or undefined when calling assessmentControllerSubmit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/assessment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitAssessmentDtoToJSON(requestParameters['submitAssessmentDto']),
        };
    }

    /**
     * Submit the onboarding assessment
     */
    async assessmentControllerSubmitRaw(requestParameters: AssessmentControllerSubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.assessmentControllerSubmitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit the onboarding assessment
     */
    async assessmentControllerSubmit(requestParameters: AssessmentControllerSubmitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assessmentControllerSubmitRaw(requestParameters, initOverrides);
    }

}
