/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthControllerGetStravaAuthUrl200Response,
  AuthControllerRefresh200Response,
  AuthControllerVerifyEmail200Response,
  AuthPayload,
  LoginDto,
  RefreshTokenDto,
  RegisterUserDto,
  StravaCallbackDto,
  VerifyEmailDto,
} from '../models/index';
import {
    AuthControllerGetStravaAuthUrl200ResponseFromJSON,
    AuthControllerGetStravaAuthUrl200ResponseToJSON,
    AuthControllerRefresh200ResponseFromJSON,
    AuthControllerRefresh200ResponseToJSON,
    AuthControllerVerifyEmail200ResponseFromJSON,
    AuthControllerVerifyEmail200ResponseToJSON,
    AuthPayloadFromJSON,
    AuthPayloadToJSON,
    LoginDtoFromJSON,
    LoginDtoToJSON,
    RefreshTokenDtoFromJSON,
    RefreshTokenDtoToJSON,
    RegisterUserDtoFromJSON,
    RegisterUserDtoToJSON,
    StravaCallbackDtoFromJSON,
    StravaCallbackDtoToJSON,
    VerifyEmailDtoFromJSON,
    VerifyEmailDtoToJSON,
} from '../models/index';

export interface AuthControllerLoginRequest {
    loginDto: LoginDto;
}

export interface AuthControllerRefreshRequest {
    refreshTokenDto: RefreshTokenDto;
}

export interface AuthControllerRegisterRequest {
    registerUserDto: RegisterUserDto;
}

export interface AuthControllerStravaCallbackRequest {
    stravaCallbackDto: StravaCallbackDto;
}

export interface AuthControllerVerifyEmailRequest {
    verifyEmailDto: VerifyEmailDto;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authControllerGetStravaAuthUrl without sending the request
     */
    async authControllerGetStravaAuthUrlRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/strava/url`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async authControllerGetStravaAuthUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthControllerGetStravaAuthUrl200Response>> {
        const requestOptions = await this.authControllerGetStravaAuthUrlRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthControllerGetStravaAuthUrl200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authControllerGetStravaAuthUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthControllerGetStravaAuthUrl200Response> {
        const response = await this.authControllerGetStravaAuthUrlRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerLogin without sending the request
     */
    async authControllerLoginRequestOpts(requestParameters: AuthControllerLoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginDto'] == null) {
            throw new runtime.RequiredError(
                'loginDto',
                'Required parameter "loginDto" was null or undefined when calling authControllerLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDtoToJSON(requestParameters['loginDto']),
        };
    }

    /**
     */
    async authControllerLoginRaw(requestParameters: AuthControllerLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPayload>> {
        const requestOptions = await this.authControllerLoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPayloadFromJSON(jsonValue));
    }

    /**
     */
    async authControllerLogin(requestParameters: AuthControllerLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPayload> {
        const response = await this.authControllerLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerRefresh without sending the request
     */
    async authControllerRefreshRequestOpts(requestParameters: AuthControllerRefreshRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refreshTokenDto'] == null) {
            throw new runtime.RequiredError(
                'refreshTokenDto',
                'Required parameter "refreshTokenDto" was null or undefined when calling authControllerRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshTokenDtoToJSON(requestParameters['refreshTokenDto']),
        };
    }

    /**
     */
    async authControllerRefreshRaw(requestParameters: AuthControllerRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthControllerRefresh200Response>> {
        const requestOptions = await this.authControllerRefreshRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthControllerRefresh200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authControllerRefresh(requestParameters: AuthControllerRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthControllerRefresh200Response | null | undefined > {
        const response = await this.authControllerRefreshRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Creates request options for authControllerRegister without sending the request
     */
    async authControllerRegisterRequestOpts(requestParameters: AuthControllerRegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerUserDto'] == null) {
            throw new runtime.RequiredError(
                'registerUserDto',
                'Required parameter "registerUserDto" was null or undefined when calling authControllerRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterUserDtoToJSON(requestParameters['registerUserDto']),
        };
    }

    /**
     */
    async authControllerRegisterRaw(requestParameters: AuthControllerRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPayload>> {
        const requestOptions = await this.authControllerRegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPayloadFromJSON(jsonValue));
    }

    /**
     */
    async authControllerRegister(requestParameters: AuthControllerRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPayload> {
        const response = await this.authControllerRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerStravaCallback without sending the request
     */
    async authControllerStravaCallbackRequestOpts(requestParameters: AuthControllerStravaCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['stravaCallbackDto'] == null) {
            throw new runtime.RequiredError(
                'stravaCallbackDto',
                'Required parameter "stravaCallbackDto" was null or undefined when calling authControllerStravaCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/strava/callback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StravaCallbackDtoToJSON(requestParameters['stravaCallbackDto']),
        };
    }

    /**
     */
    async authControllerStravaCallbackRaw(requestParameters: AuthControllerStravaCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPayload>> {
        const requestOptions = await this.authControllerStravaCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPayloadFromJSON(jsonValue));
    }

    /**
     */
    async authControllerStravaCallback(requestParameters: AuthControllerStravaCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPayload> {
        const response = await this.authControllerStravaCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerVerifyEmail without sending the request
     */
    async authControllerVerifyEmailRequestOpts(requestParameters: AuthControllerVerifyEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyEmailDto'] == null) {
            throw new runtime.RequiredError(
                'verifyEmailDto',
                'Required parameter "verifyEmailDto" was null or undefined when calling authControllerVerifyEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/verify-email`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEmailDtoToJSON(requestParameters['verifyEmailDto']),
        };
    }

    /**
     */
    async authControllerVerifyEmailRaw(requestParameters: AuthControllerVerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthControllerVerifyEmail200Response>> {
        const requestOptions = await this.authControllerVerifyEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthControllerVerifyEmail200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authControllerVerifyEmail(requestParameters: AuthControllerVerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthControllerVerifyEmail200Response | null | undefined > {
        const response = await this.authControllerVerifyEmailRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return null;
            default:
                return await response.value();
        }
    }

}
