/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthPayload,
  LoginInput,
  RegisterUserInput,
} from '../models/index';
import {
    AuthPayloadFromJSON,
    AuthPayloadToJSON,
    LoginInputFromJSON,
    LoginInputToJSON,
    RegisterUserInputFromJSON,
    RegisterUserInputToJSON,
} from '../models/index';

export interface AuthControllerLoginRequest {
    loginInput: LoginInput;
}

export interface AuthControllerRegisterRequest {
    registerUserInput: RegisterUserInput;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authControllerLogin without sending the request
     */
    async authControllerLoginRequestOpts(requestParameters: AuthControllerLoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginInput'] == null) {
            throw new runtime.RequiredError(
                'loginInput',
                'Required parameter "loginInput" was null or undefined when calling authControllerLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginInputToJSON(requestParameters['loginInput']),
        };
    }

    /**
     */
    async authControllerLoginRaw(requestParameters: AuthControllerLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPayload>> {
        const requestOptions = await this.authControllerLoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPayloadFromJSON(jsonValue));
    }

    /**
     */
    async authControllerLogin(requestParameters: AuthControllerLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPayload> {
        const response = await this.authControllerLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authControllerRegister without sending the request
     */
    async authControllerRegisterRequestOpts(requestParameters: AuthControllerRegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerUserInput'] == null) {
            throw new runtime.RequiredError(
                'registerUserInput',
                'Required parameter "registerUserInput" was null or undefined when calling authControllerRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterUserInputToJSON(requestParameters['registerUserInput']),
        };
    }

    /**
     */
    async authControllerRegisterRaw(requestParameters: AuthControllerRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthPayload>> {
        const requestOptions = await this.authControllerRegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthPayloadFromJSON(jsonValue));
    }

    /**
     */
    async authControllerRegister(requestParameters: AuthControllerRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthPayload> {
        const response = await this.authControllerRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
