/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGoalDto,
} from '../models/index';
import {
    CreateGoalDtoFromJSON,
    CreateGoalDtoToJSON,
} from '../models/index';

export interface GoalsControllerCreateRequest {
    createGoalDto: CreateGoalDto;
}

/**
 * 
 */
export class GoalsApi extends runtime.BaseAPI {

    /**
     * Creates request options for goalsControllerCreate without sending the request
     */
    async goalsControllerCreateRequestOpts(requestParameters: GoalsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createGoalDto'] == null) {
            throw new runtime.RequiredError(
                'createGoalDto',
                'Required parameter "createGoalDto" was null or undefined when calling goalsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/goals`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGoalDtoToJSON(requestParameters['createGoalDto']),
        };
    }

    /**
     * Criar objetivo de corrida em texto livre
     */
    async goalsControllerCreateRaw(requestParameters: GoalsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.goalsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar objetivo de corrida em texto livre
     */
    async goalsControllerCreate(requestParameters: GoalsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.goalsControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for goalsControllerGetActive without sending the request
     */
    async goalsControllerGetActiveRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/goals/active`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Buscar objetivo ativo do usuário
     */
    async goalsControllerGetActiveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.goalsControllerGetActiveRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Buscar objetivo ativo do usuário
     */
    async goalsControllerGetActive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.goalsControllerGetActiveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for goalsControllerList without sending the request
     */
    async goalsControllerListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/goals`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Listar todos os objetivos do usuário
     */
    async goalsControllerListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.goalsControllerListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todos os objetivos do usuário
     */
    async goalsControllerList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.goalsControllerListRaw(initOverrides);
    }

}
