/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface IntegrationsControllerConnectIntegrationRequest {
    integrationId: string;
}

export interface IntegrationsControllerDisconnectIntegrationRequest {
    integrationId: string;
}

export interface IntegrationsControllerHandleStravaCallbackRequest {
    body: object;
}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for integrationsControllerConnectIntegration without sending the request
     */
    async integrationsControllerConnectIntegrationRequestOpts(requestParameters: IntegrationsControllerConnectIntegrationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling integrationsControllerConnectIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/integrations/{integrationId}/connect`;
        urlPath = urlPath.replace(`{${"integrationId"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerConnectIntegrationRaw(requestParameters: IntegrationsControllerConnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerConnectIntegrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerConnectIntegration(requestParameters: IntegrationsControllerConnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerConnectIntegrationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for integrationsControllerDisconnectIntegration without sending the request
     */
    async integrationsControllerDisconnectIntegrationRequestOpts(requestParameters: IntegrationsControllerDisconnectIntegrationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling integrationsControllerDisconnectIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/integrations/{integrationId}/disconnect`;
        urlPath = urlPath.replace(`{${"integrationId"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerDisconnectIntegrationRaw(requestParameters: IntegrationsControllerDisconnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerDisconnectIntegrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerDisconnectIntegration(requestParameters: IntegrationsControllerDisconnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerDisconnectIntegrationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for integrationsControllerDisconnectStrava without sending the request
     */
    async integrationsControllerDisconnectStravaRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/integrations/strava/disconnect`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerDisconnectStravaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerDisconnectStravaRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerDisconnectStrava(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerDisconnectStravaRaw(initOverrides);
    }

    /**
     * Creates request options for integrationsControllerGetStravaAuthUrl without sending the request
     */
    async integrationsControllerGetStravaAuthUrlRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/integrations/strava/auth`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerGetStravaAuthUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerGetStravaAuthUrlRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerGetStravaAuthUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerGetStravaAuthUrlRaw(initOverrides);
    }

    /**
     * Creates request options for integrationsControllerHandleStravaCallback without sending the request
     */
    async integrationsControllerHandleStravaCallbackRequestOpts(requestParameters: IntegrationsControllerHandleStravaCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling integrationsControllerHandleStravaCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/integrations/strava/callback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async integrationsControllerHandleStravaCallbackRaw(requestParameters: IntegrationsControllerHandleStravaCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerHandleStravaCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerHandleStravaCallback(requestParameters: IntegrationsControllerHandleStravaCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerHandleStravaCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for integrationsControllerIntegrations without sending the request
     */
    async integrationsControllerIntegrationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/integrations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerIntegrationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerIntegrationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerIntegrations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerIntegrationsRaw(initOverrides);
    }

    /**
     * Creates request options for integrationsControllerSyncStrava without sending the request
     */
    async integrationsControllerSyncStravaRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/integrations/strava/sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerSyncStravaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerSyncStravaRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerSyncStrava(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerSyncStravaRaw(initOverrides);
    }

}
