/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface TrainingPlansControllerCreateTrainingPlanRequest {
    body: object;
}

export interface TrainingPlansControllerDeleteTrainingPlanRequest {
    id: string;
}

export interface TrainingPlansControllerGetTrainingPlanByIdRequest {
    id: string;
}

export interface TrainingPlansControllerUpdateTrainingPlanRequest {
    id: string;
    body: object;
}

/**
 * 
 */
export class TrainingPlansApi extends runtime.BaseAPI {

    /**
     * Creates request options for trainingPlansControllerCreateTrainingPlan without sending the request
     */
    async trainingPlansControllerCreateTrainingPlanRequestOpts(requestParameters: TrainingPlansControllerCreateTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling trainingPlansControllerCreateTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/training-plans`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async trainingPlansControllerCreateTrainingPlanRaw(requestParameters: TrainingPlansControllerCreateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.trainingPlansControllerCreateTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async trainingPlansControllerCreateTrainingPlan(requestParameters: TrainingPlansControllerCreateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingPlansControllerCreateTrainingPlanRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for trainingPlansControllerDeleteTrainingPlan without sending the request
     */
    async trainingPlansControllerDeleteTrainingPlanRequestOpts(requestParameters: TrainingPlansControllerDeleteTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPlansControllerDeleteTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/training-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async trainingPlansControllerDeleteTrainingPlanRaw(requestParameters: TrainingPlansControllerDeleteTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.trainingPlansControllerDeleteTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async trainingPlansControllerDeleteTrainingPlan(requestParameters: TrainingPlansControllerDeleteTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingPlansControllerDeleteTrainingPlanRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for trainingPlansControllerGetMyTrainingPlan without sending the request
     */
    async trainingPlansControllerGetMyTrainingPlanRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/training-plans/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async trainingPlansControllerGetMyTrainingPlanRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.trainingPlansControllerGetMyTrainingPlanRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async trainingPlansControllerGetMyTrainingPlan(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingPlansControllerGetMyTrainingPlanRaw(initOverrides);
    }

    /**
     * Creates request options for trainingPlansControllerGetTrainingPlanById without sending the request
     */
    async trainingPlansControllerGetTrainingPlanByIdRequestOpts(requestParameters: TrainingPlansControllerGetTrainingPlanByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPlansControllerGetTrainingPlanById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/training-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async trainingPlansControllerGetTrainingPlanByIdRaw(requestParameters: TrainingPlansControllerGetTrainingPlanByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.trainingPlansControllerGetTrainingPlanByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async trainingPlansControllerGetTrainingPlanById(requestParameters: TrainingPlansControllerGetTrainingPlanByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingPlansControllerGetTrainingPlanByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for trainingPlansControllerUpdateTrainingPlan without sending the request
     */
    async trainingPlansControllerUpdateTrainingPlanRequestOpts(requestParameters: TrainingPlansControllerUpdateTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPlansControllerUpdateTrainingPlan().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling trainingPlansControllerUpdateTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/training-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async trainingPlansControllerUpdateTrainingPlanRaw(requestParameters: TrainingPlansControllerUpdateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.trainingPlansControllerUpdateTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async trainingPlansControllerUpdateTrainingPlan(requestParameters: TrainingPlansControllerUpdateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingPlansControllerUpdateTrainingPlanRaw(requestParameters, initOverrides);
    }

}
