/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWaitlistEntryDto,
} from '../models/index';
import {
    CreateWaitlistEntryDtoFromJSON,
    CreateWaitlistEntryDtoToJSON,
} from '../models/index';

export interface WaitlistControllerCreateRequest {
    createWaitlistEntryDto: CreateWaitlistEntryDto;
}

/**
 * 
 */
export class WaitlistApi extends runtime.BaseAPI {

    /**
     * Creates request options for waitlistControllerCreate without sending the request
     */
    async waitlistControllerCreateRequestOpts(requestParameters: WaitlistControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWaitlistEntryDto'] == null) {
            throw new runtime.RequiredError(
                'createWaitlistEntryDto',
                'Required parameter "createWaitlistEntryDto" was null or undefined when calling waitlistControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/waitlist`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWaitlistEntryDtoToJSON(requestParameters['createWaitlistEntryDto']),
        };
    }

    /**
     * Cadastrar na lista de espera
     */
    async waitlistControllerCreateRaw(requestParameters: WaitlistControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.waitlistControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cadastrar na lista de espera
     */
    async waitlistControllerCreate(requestParameters: WaitlistControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.waitlistControllerCreateRaw(requestParameters, initOverrides);
    }

}
