/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface WeeklyGoalsControllerCreateWeeklyGoalRequest {
    body: object;
}

export interface WeeklyGoalsControllerDeleteWeeklyGoalRequest {
    uuid: string;
}

export interface WeeklyGoalsControllerGetWeeklyGoalByIdRequest {
    uuid: string;
}

export interface WeeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRequest {
    trainingPlanId: string;
}

export interface WeeklyGoalsControllerUpdateWeeklyGoalRequest {
    uuid: string;
    body: object;
}

/**
 * 
 */
export class WeeklyGoalsApi extends runtime.BaseAPI {

    /**
     * Creates request options for weeklyGoalsControllerCreateWeeklyGoal without sending the request
     */
    async weeklyGoalsControllerCreateWeeklyGoalRequestOpts(requestParameters: WeeklyGoalsControllerCreateWeeklyGoalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling weeklyGoalsControllerCreateWeeklyGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/weekly-goals`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async weeklyGoalsControllerCreateWeeklyGoalRaw(requestParameters: WeeklyGoalsControllerCreateWeeklyGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.weeklyGoalsControllerCreateWeeklyGoalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async weeklyGoalsControllerCreateWeeklyGoal(requestParameters: WeeklyGoalsControllerCreateWeeklyGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.weeklyGoalsControllerCreateWeeklyGoalRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for weeklyGoalsControllerDeleteWeeklyGoal without sending the request
     */
    async weeklyGoalsControllerDeleteWeeklyGoalRequestOpts(requestParameters: WeeklyGoalsControllerDeleteWeeklyGoalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling weeklyGoalsControllerDeleteWeeklyGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/weekly-goals/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async weeklyGoalsControllerDeleteWeeklyGoalRaw(requestParameters: WeeklyGoalsControllerDeleteWeeklyGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.weeklyGoalsControllerDeleteWeeklyGoalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async weeklyGoalsControllerDeleteWeeklyGoal(requestParameters: WeeklyGoalsControllerDeleteWeeklyGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.weeklyGoalsControllerDeleteWeeklyGoalRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for weeklyGoalsControllerGetWeeklyGoalById without sending the request
     */
    async weeklyGoalsControllerGetWeeklyGoalByIdRequestOpts(requestParameters: WeeklyGoalsControllerGetWeeklyGoalByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling weeklyGoalsControllerGetWeeklyGoalById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/weekly-goals/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async weeklyGoalsControllerGetWeeklyGoalByIdRaw(requestParameters: WeeklyGoalsControllerGetWeeklyGoalByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.weeklyGoalsControllerGetWeeklyGoalByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async weeklyGoalsControllerGetWeeklyGoalById(requestParameters: WeeklyGoalsControllerGetWeeklyGoalByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.weeklyGoalsControllerGetWeeklyGoalByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for weeklyGoalsControllerGetWeeklyGoalsByTrainingPlan without sending the request
     */
    async weeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRequestOpts(requestParameters: WeeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainingPlanId'] == null) {
            throw new runtime.RequiredError(
                'trainingPlanId',
                'Required parameter "trainingPlanId" was null or undefined when calling weeklyGoalsControllerGetWeeklyGoalsByTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/weekly-goals/training-plan/{trainingPlanId}`;
        urlPath = urlPath.replace(`{${"trainingPlanId"}}`, encodeURIComponent(String(requestParameters['trainingPlanId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async weeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRaw(requestParameters: WeeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.weeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async weeklyGoalsControllerGetWeeklyGoalsByTrainingPlan(requestParameters: WeeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.weeklyGoalsControllerGetWeeklyGoalsByTrainingPlanRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for weeklyGoalsControllerUpdateWeeklyGoal without sending the request
     */
    async weeklyGoalsControllerUpdateWeeklyGoalRequestOpts(requestParameters: WeeklyGoalsControllerUpdateWeeklyGoalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling weeklyGoalsControllerUpdateWeeklyGoal().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling weeklyGoalsControllerUpdateWeeklyGoal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/weekly-goals/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async weeklyGoalsControllerUpdateWeeklyGoalRaw(requestParameters: WeeklyGoalsControllerUpdateWeeklyGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.weeklyGoalsControllerUpdateWeeklyGoalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async weeklyGoalsControllerUpdateWeeklyGoal(requestParameters: WeeklyGoalsControllerUpdateWeeklyGoalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.weeklyGoalsControllerUpdateWeeklyGoalRaw(requestParameters, initOverrides);
    }

}
