/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface WorkoutsControllerCompleteWorkoutRequest {
    workoutId: string;
}

export interface WorkoutsControllerCreateWorkoutRequest {
    body: object;
}

export interface WorkoutsControllerSkipWorkoutRequest {
    workoutId: string;
}

export interface WorkoutsControllerSubmitWorkoutFeedbackRequest {
    workoutId: string;
    body: object;
}

export interface WorkoutsControllerUpdateWorkoutRequest {
    workoutId: string;
    body: object;
}

export interface WorkoutsControllerWorkoutRequest {
    id: string;
}

export interface WorkoutsControllerWorkoutsByTrainingPlanRequest {
    trainingPlanId: string;
}

/**
 * 
 */
export class WorkoutsApi extends runtime.BaseAPI {

    /**
     * Creates request options for workoutsControllerCompleteWorkout without sending the request
     */
    async workoutsControllerCompleteWorkoutRequestOpts(requestParameters: WorkoutsControllerCompleteWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerCompleteWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/{workoutId}/complete`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerCompleteWorkoutRaw(requestParameters: WorkoutsControllerCompleteWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerCompleteWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerCompleteWorkout(requestParameters: WorkoutsControllerCompleteWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerCompleteWorkoutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workoutsControllerCreateWorkout without sending the request
     */
    async workoutsControllerCreateWorkoutRequestOpts(requestParameters: WorkoutsControllerCreateWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling workoutsControllerCreateWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workouts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async workoutsControllerCreateWorkoutRaw(requestParameters: WorkoutsControllerCreateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerCreateWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerCreateWorkout(requestParameters: WorkoutsControllerCreateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerCreateWorkoutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workoutsControllerSkipWorkout without sending the request
     */
    async workoutsControllerSkipWorkoutRequestOpts(requestParameters: WorkoutsControllerSkipWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerSkipWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/{workoutId}/skip`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerSkipWorkoutRaw(requestParameters: WorkoutsControllerSkipWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerSkipWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerSkipWorkout(requestParameters: WorkoutsControllerSkipWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerSkipWorkoutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workoutsControllerSubmitWorkoutFeedback without sending the request
     */
    async workoutsControllerSubmitWorkoutFeedbackRequestOpts(requestParameters: WorkoutsControllerSubmitWorkoutFeedbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerSubmitWorkoutFeedback().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling workoutsControllerSubmitWorkoutFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workouts/{workoutId}/feedback`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async workoutsControllerSubmitWorkoutFeedbackRaw(requestParameters: WorkoutsControllerSubmitWorkoutFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerSubmitWorkoutFeedbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerSubmitWorkoutFeedback(requestParameters: WorkoutsControllerSubmitWorkoutFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerSubmitWorkoutFeedbackRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workoutsControllerTodayWorkout without sending the request
     */
    async workoutsControllerTodayWorkoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/today`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerTodayWorkoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerTodayWorkoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerTodayWorkout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerTodayWorkoutRaw(initOverrides);
    }

    /**
     * Creates request options for workoutsControllerUpdateWorkout without sending the request
     */
    async workoutsControllerUpdateWorkoutRequestOpts(requestParameters: WorkoutsControllerUpdateWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerUpdateWorkout().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling workoutsControllerUpdateWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workouts/{workoutId}`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async workoutsControllerUpdateWorkoutRaw(requestParameters: WorkoutsControllerUpdateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerUpdateWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerUpdateWorkout(requestParameters: WorkoutsControllerUpdateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerUpdateWorkoutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workoutsControllerWorkout without sending the request
     */
    async workoutsControllerWorkoutRequestOpts(requestParameters: WorkoutsControllerWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workoutsControllerWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerWorkoutRaw(requestParameters: WorkoutsControllerWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerWorkout(requestParameters: WorkoutsControllerWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerWorkoutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for workoutsControllerWorkoutHistory without sending the request
     */
    async workoutsControllerWorkoutHistoryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerWorkoutHistoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerWorkoutHistoryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerWorkoutHistory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerWorkoutHistoryRaw(initOverrides);
    }

    /**
     * Creates request options for workoutsControllerWorkoutsByTrainingPlan without sending the request
     */
    async workoutsControllerWorkoutsByTrainingPlanRequestOpts(requestParameters: WorkoutsControllerWorkoutsByTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainingPlanId'] == null) {
            throw new runtime.RequiredError(
                'trainingPlanId',
                'Required parameter "trainingPlanId" was null or undefined when calling workoutsControllerWorkoutsByTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/training-plan/{trainingPlanId}`;
        urlPath = urlPath.replace(`{${"trainingPlanId"}}`, encodeURIComponent(String(requestParameters['trainingPlanId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerWorkoutsByTrainingPlanRaw(requestParameters: WorkoutsControllerWorkoutsByTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.workoutsControllerWorkoutsByTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async workoutsControllerWorkoutsByTrainingPlan(requestParameters: WorkoutsControllerWorkoutsByTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.workoutsControllerWorkoutsByTrainingPlanRaw(requestParameters, initOverrides);
    }

}
